### ISSUE TITLE
Preact onClick only works for first element

### ISSUE THREAD

**Issue by dan-flux-capacity** [muenzpraeger/sfdx-lwc-preact-svelte-vue-example#1]
When clicking on an Account row in the Preact example, the component only returns the Id of the first element in the list, regardless of which row is clicked. I've observed similar behavior in other projects that utilize Preact in an LWC I've been working on, where the first element rendered with an onClick property is the only onclick functioned executed, no matter where on the component is clicked, or if other elements also have an onClick property. Do you have any suggestions as to what would cause that issue, and/or ways to address that?

**Comment by muenzpraeger** [comment]
Interesting. Is that within an org, or does that also happen on local dev? Just did a quick test run on the latter, and everything works as expected.


https://user-images.githubusercontent.com/2205451/104222638-ddc23880-5442-11eb-9080-c5f87aa46e19.mp4

**Comment by dan-flux-capacity** [comment]
Oh yeah, that is interesting. I ran into some trouble getting the local up and running when I was installing, so just did a scratch org. Based on that, sounds like this is a Locker Service issue then?

**Comment by muenzpraeger** [comment]
Just reproduced within an org. So yes, it could be based on Locker. But not sure, and eventually it'd be hard to debug.
