### ISSUE TITLE
Svelte: Uncaught (in promise) Error: Disallowed method "getElementById" in ShadowRoot.

### ISSUE THREAD

**Issue by jesstucker** [muenzpraeger/sfdx-lwc-preact-svelte-vue-example#3]
Just a wild guess – svelte doesn't use a shadow dom, and this is causing an error in the generated `force-app/main/default/lwc/svelte/svelte.js`, line 32 here:

```javascript
function append_styles(target, style_sheet_id, styles) {
    const append_styles_to = get_root_for_style(target);
    if (!append_styles_to.getElementById(style_sheet_id)) { //here
 // if (!append_styles_to.querySelector(`#${style_sheet_id}`)) { // just for kicks, if I modify this to a query selector, it seems to work. but rollup will regenerate this file, overwriting my change.
        const style = element('style');
        style.id = style_sheet_id;
        style.textContent = styles;
        append_stylesheet(append_styles_to, style);
    }
}
```
<img width="1624" alt="Screen Shot 2022-06-25 at 8 02 39 PM" src="https://user-images.githubusercontent.com/3093012/175794118-c47d35c9-83c2-4741-96ad-56ac7723e8ba.png">

As commented above, I modified line 32 to use a query selector, it seems to work. but rollup will regenerate this file, overwriting my change.

See here:

<img width="1624" alt="Screen Shot 2022-06-25 at 8 12 01 PM" src="https://user-images.githubusercontent.com/3093012/175794316-48def4ff-39df-487e-bb73-93e5ea80a1bc.png">

Is this example repo more or less deprecated?
I'm having other issues with using node v18 as well

Nonetheless, bless you for providing this example! 🙏

**Comment by jesstucker** [comment]
Stuff that seems to wreck the deploy (because it's changing `force-app/main/default/lwc/svelte/svelte.js`:
- Changing the `package-lock.json` ( deleting the old one or migrating the examples to a new project )
- Running `npm run build` or `npm run dev`, which updates the code in `force-app/main/default/lwc/svelte/svelte.js`
- Using newer node, I tried running `npm i` and it doesn't like the out of date chokidar stuff

Is there a way to debug? I'm curious if it might be locker service related. I'm not sure it's possible to use svelte with this level of trouble?

**Comment by muenzpraeger** [comment]
Thanks for reaching out, @jesstucker.

This repo is a bit old, and eventually not fully up-to-date with how things work these days. From what it looks like there is a new check within LWC that prevents the usage of `getElementById`.

You can hack your way around that by modifying the code after Rollup generated the ESM from Svelte. See [here](https://github.com/muenzpraeger/sfdx-lwc-preact-svelte-vue-example/blob/rw/updates-2022/scripts/rollup.svelte.js#L30-L42) and [line 19](https://github.com/muenzpraeger/sfdx-lwc-preact-svelte-vue-example/blob/rw/updates-2022/scripts/rollup.svelte.js#L19) how such a hack would look like (it's a bit hand waivy, but should give you a starter).

**Comment by jesstucker** [comment]
@muenzpraeger Haha! That's an interesting solution!

Is this basically Lightning Locker? If so, is there a place I can read more about how to follow its rules, and get it to return meaningful errors?

And would you consider bringing in another framework such as React or Svelte a hack at best? Is likely to always be an uphill battle?

Thanks @muenzpraeger, I really appreciate it.

**Comment by muenzpraeger** [comment]
That is not Locker, but a restriction within LWC.

For now I'd say such a modification is something to carefully look at. Mixing up frameworks can quickly become a (maintenance) challenge on its own.

**Comment by jesstucker** [comment]
Thanks for advising René. Will steer clear for the time being!
